##
# npm-package-release.yaml
# Will publish NPM package to GitHub Packages.
##
---
name: Release

on:
  pull_request:
    types: ['closed']
    branches: ['main']

  workflow_dispatch:
    inputs:
      package_version_type:
        required: true
        description: Select semantic version type
        type: choice
        options:
          - major
          - minor
          - patch
          
jobs:
  call-reusable-workflow:
    name: Reusable
    # permissions:
    #   contents: read
    #   packages: write
    uses: icebreakeros/reusable-workflow/.github/workflows/npm-package-release.yaml@main
    secrets: inherit
    with:
      package_version_type: ${{ github.event.inputs.package_version_type }}
